### ISSUE TITLE
Wrong interface package extension?

### ISSUE THREAD

**Issue by quinnj** [queryverse/VegaDatasets.jl#13]
On [this line](https://github.com/queryverse/VegaDatasets.jl/blob/master/src/VegaDatasets.jl#L21), shouldn't it extend `IteratorInterfaceExtensions` instead of `TableTraits`? I know they end up extending the same method, but it seems more correct to extend the method from the originating module.

**Comment by davidanthoff** [comment]
Yes, thanks for reporting!
